### ISSUE TITLE
slowdown after some time 

### ISSUE THREAD

**Issue by clojj** [serras/HaskellsGameOfLife#1]
Noticed that after about 80 animation frames, the display updates slower and several generations are dropped... 
is this a known problem with gloom´s animate function?

**Comment by serras** [comment]
No, it's actually a problem of the implementation, which never drops any information about older generations. As a result, memory consumption explodes and this reveals itself as slowdown.
So Gloss is pretty fine, the problem is in my code :(

**Comment by clojj** [comment]
ok... didn't try it yet, but I guess that `gameOfLifeSuperSlow` will not show this behavior ?

**Comment by serras** [comment]
It will also run slower each time, but for a different reason: each round it needs to recompute all the previous generations.
